version: '3.5'
services: 
  vault:
    image: $IMAGE
    container_name: $CONTAINER_NAME
    ports: 
      - $PORT:$PORT
    restart: always
    volumes: 
      - ./vault/file:/vault/file
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - .vault/data:/vault/data
    environment: 
      - VAULT_ADDR=$VAULT_ADDR
      - VAULT_API_ADDR=$VAULT_API_ADDR
      - VAULT_ADDRESS=$VAULT_ADDRESS
    cap_add: 
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
networks: 
  default:
    name: $NETWORKS
